kind: pipeline
type: exec
name: macOS

platform:
  os: darwin

steps:
- name: build
  environment:
    ASDF_DIR: /opt/homebrew/opt/asdf
    ASDF_DATA_DIR: /Users/snapask-ci/.asdf
  commands:
  - export PATH=/opt/homebrew/bin:$PATH
  - . $(brew --prefix asdf)/asdf.sh
  - export

---
kind: pipeline
type: docker
name: slack
steps:
- name: slack
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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

trigger:
  event:
  - cron
  - custom
  # - push
  - pull_request
  - tag
  - promote
  - rollback
